CREATE DATABASE IF NOT EXISTS aula_php;

USE aula_php;

CREATE TABLE IF NOT EXISTS usuarios (
    codigo INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    administrador TINYINT(1) NOT NULL DEFAULT 0
);
